### ISSUE TITLE
AR Camera / Vuforia

### ISSUE THREAD

**Issue by emorling** [ryanw3bb/unity-native-toolkit#10]
Is it possible to use this with an AR Camera from Vuforia? 

For example only initialize the Native Toolkit in a separate Scene not using an AR Camera?

**Comment by ryanw3bb** [comment]
Yes it should be possible to use Native Toolkit in the same project as Vuforia if that is what you're asking.

**Comment by emorling** [comment]
Whenever Native Toolkit is in the Unity Project, the AR Camera just renders black. It appears there is some kind of "race" for the camera?

**Comment by uokivan** [comment]
When use the AR Camera, it's already use the camera from your phone, just use capture screenshot can make it

**Comment by emorling** [comment]
The AR Camera does not work (only renders Black) if Native Toolkit is in the project. So you can neither use the AR features or screenshot anything

**Comment by muckletone** [comment]
Just to confirm, we are seeing the same issue as emorling has posted. If Native Toolkit is part of the project, the AR Camera is either been disabled or renders solid black.

**Comment by thylaxene** [comment]
Yes I can confirm this is certainly an issue. I've seen in in Unity 2018.3 and 2019.1. Vuforia just renders black screen. As soon as you remove NT all is fine again.

**Comment by ryanw3bb** [comment]
This has been fixed now - have reverted back to using uncompiled classes for iOS instead of a static lib. In this instance it was conflicting with Vuforia as they both try to override UnityAppController.
