### ISSUE TITLE
Need Help

### ISSUE THREAD

**Issue by stefanodias** [ryanw3bb/unity-native-toolkit#12]
I trying compiling on Xcode 10.1 with Unity3D 2018.3.5f1 but no work.. the message I received "Invalid bitcode signature"

**Comment by Kruegbert** [comment]
Same here. Building with Unity3D (5.6.4f1) works, even building directly on a device via xCode. But we get the same error when archiving.
Already went through every error-solution - still not working.
- Disabling bitcode does not work, since its a static library

**Comment by ryanw3bb** [comment]
Do a fresh pull and it should archive fine with bitcode disabled now. 

Seems like the lesser of 2 evils to disable bitcode in the static library, then if anyone really needs it they can rebuild it using the Xcode project and their desired architectures.

**Comment by Kruegbert** [comment]
Hi Ryan, thanks for the update. Unfortunately we want to build with bitcode. Gladly we found the 'UnityNativeGallery' plugin for Unity and it seems to work with bitcode. Maybe you can get connected with them to make yours possible with bitcode as well?
Anyway, thanks for your work!
