### ISSUE TITLE
FEATURE REQUEST: get Accuracy and other info from location (ios/android)

### ISSUE THREAD

**Issue by pap3rinik** [ryanw3bb/unity-native-toolkit#14]
it is great you get double precision latitude and longitude with this native plugin, would be more tha great if you would add access to mopre location info (suche as accuracy/speed/etc)

**Comment by ryanw3bb** [comment]
Unfortunately I have no time to implement new features currently, but I will add this to the road map. Feel free to contribute to the repository if you make the suggested changes.
