### ISSUE TITLE
App crushed when using camera shot

### ISSUE THREAD

**Issue by rozx** [ryanw3bb/unity-native-toolkit#2]
>     java.lang.RuntimeException: Unable to start activity ComponentInfo{com.hitgrab.playground/com.secondfury.nativetoolkit.MainActivity}: android.os.FileUriExposedException: file:///storage/emulated/0/Pictures/Camera/IMG_20181120_145452.jpg exposed beyond app through ClipData.Item.getUri()
>         at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2913)
>         at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3048)
>         at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
>         at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
>         at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
>         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808)
>         at android.os.Handler.dispatchMessage(Handler.java:106)
>         at android.os.Looper.loop(Looper.java:193)
>         at android.app.ActivityThread.main(ActivityThread.java:6669)
>         at java.lang.reflect.Method.invoke(Native Method)
>         at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
>         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
>      Caused by: android.os.FileUriExposedException: file:///storage/emulated/0/Pictures/Camera/IMG_20181120_145452.jpg exposed beyond app through ClipData.Item.getUri()
>         at android.os.StrictMode.onFileUriExposed(StrictMode.java:1978)
>         at android.net.Uri.checkFileUriExposed(Uri.java:2371)
>         at android.content.ClipData.prepareToLeaveProcess(ClipData.java:963)
>         at android.content.Intent.prepareToLeaveProcess(Intent.java:10216)
>         at android.content.Intent.prepareToLeaveProcess(Intent.java:10201)
>         at android.app.Instrumentation.execStartActivity(Instrumentation.java:1667)
>         at android.app.Activity.startActivityForResult(Activity.java:4586)
>         at android.app.Activity.startActivityForResult(Activity.java:4544)
>         at com.secondfury.nativetoolkit.MainActivity.onCreate(MainActivity.java:59)
>         at android.app.Activity.performCreate(Activity.java:7136)
>         at android.app.Activity.performCreate(Activity.java:7127)
>         at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
>         at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2893)
>         at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3048) 
>         at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78) 
>         at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108) 
>         at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68) 
>         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808) 
>         at android.os.Handler.dispatchMessage(Handler.java:106) 
>         at android.os.Looper.loop(Looper.java:193) 
>         at android.app.ActivityThread.main(ActivityThread.java:6669) 
>         at java.lang.reflect.Method.invoke(Native Method) 
>         at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
>         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858) 

using emulation device, API level 28, all permissions granted.

**Comment by ryanw3bb** [comment]
Fixed as of the latest commit

**Comment by ajinkyapuar** [comment]
I'm facing the same issue
Unity version : 2019.1.0f2
Android version : 8.1.0
