### ISSUE TITLE
API for viewing files

### ISSUE THREAD

**Issue by bigdavedev** [ryanw3bb/unity-native-toolkit#20]
I would like to propose an API for sending a VIEW intent such that, on Android at least, I may present files such as PDFs and images in the appropriate external application.

This is trivial for the Android case, since the intent is formed similarly to the e-mail intent, but I have no experience with iOS in this regard. Do you foresee any issues with this proposal?

**Comment by ryanw3bb** [comment]
Hi @bigdavedev, I see no reason why that shouldn't work on iOS. Feel free to contribute to the repository through a pull request if you add any new features.
