### ISSUE TITLE
strange highlight on photo review

### ISSUE THREAD

**Issue by SimssmiS** [ryanw3bb/unity-native-toolkit#24]
Hey, I've got this strange highlight when reviewing the image taken. Any way to modify or remove it?
![IMG_880AE3649CE1-1](https://user-images.githubusercontent.com/5853825/59690393-a7c6bf00-91e1-11e9-88f8-a0e05fc15fff.jpeg)

**Comment by ryanw3bb** [comment]
In Plugins/iOS/Camera.mm comment out picker.allowsEditing = YES;
