### ISSUE TITLE
Calling TargetGuidByName with name='Unity-iPhone' is deprecated. 

### ISSUE THREAD

**Issue by Goncharuk-Nikita** [ryanw3bb/unity-native-toolkit#26]
**Unity 2019.3.0b9**  iOS

The issue occurs in **PostProcessor.cs :24**

![image](https://user-images.githubusercontent.com/30652592/68339765-7b0a3a00-00e5-11ea-8f54-c7b4a3f12e01.png)
![image](https://user-images.githubusercontent.com/30652592/68339803-8cebdd00-00e5-11ea-99ce-d1d32151d191.png)

**Comment by leoncvlt** [comment]
This can be fixed by replacing that line with `string targetGuid = proj.GetUnityMainTargetGuid();` - Tested in Unity 2019.3.0f6

**Comment by Elmundo** [comment]
@leoncvlt where can i find PostProcessor.cs file? I've tried to find it in a few place but could not find unfortunately.

**Comment by Goncharuk-Nikita** [comment]
Fixed in later versions of Unity

**Comment by AbrarAmin1** [comment]
> Fixed in later versions of Unity

Which version? I am using 2019.3.3f1 released yesterday and i am facing this issue

**Comment by RaschidJFR** [comment]
I had the same problem as you @AbrarAmin1 . It turnes out that one of my plugins was using this outdated script. I did a global code search for `TargetGuidByName` that led me to the culprit line so that I could update it.

**Comment by SaidSoria** [comment]
> This can be fixed by replacing that line with `string targetGuid = proj.GetUnityMainTargetGuid();` - Tested in Unity 2019.3.0f6

This solution helped me! 
Unity Version: 2019.3.9f1

Just added this code: 
`proj.AddFrameworkToProject(proj.GetUnityMainTargetGuid(), "ARKit.framework", false);
string target = proj.GetUnityMainTargetGuid();`

**Comment by mavc18** [comment]
where is the file .cs to change? i cant find in my unity proyect
