### ISSUE TITLE
Crashes on Android

### ISSUE THREAD

**Issue by cadmicro** [ryanw3bb/unity-native-toolkit#3]
Running the example on Android api 27 crashes instantly.

**Comment by ryanw3bb** [comment]
Could you give some more information about the running environment - is this on device or emulator?

**Comment by ryanw3bb** [comment]
Thanks for your reply, it does sound like a permissions issue. The Android lib has recently been rebuilt using API 27, would you be able to do a pull and fresh install on your device and try again.

When running the demo scene on a Pixel 2 I get 5x permission requests on start.

**Comment by cadmicro** [comment]
How it is running however it does not ask for permission, and none of the buttons function when clicked. I started a fresh project and imported your unity files, minimum apk 26.

**Comment by ryanw3bb** [comment]
Have the buttons OnClick listeners come unlinked? Is the Example script on the "Code" GameObject and linked? What version of Unity are you running on? Try Unity 2018.2.11 or later and do a fresh asset import (Assets -> Reimport All)

**Comment by cadmicro** [comment]
Hahahaha..... yes... you are correct. Thanks. I will test and let you know.
________________________________

**Comment by kushal98** [comment]
hey @ryanw3bb , I am also facing the same issue but only for the open camera option its working on one phone with API level 27 but not working on the other with same API level 27 and also not working on some other android phone( one plus 5 ).
android phone on which it is working is POCO F1 and the one in which it is not working is Moto G5 SPlus

**Comment by ryanw3bb** [comment]
@kushal98 sounds like a separate issue, if it is still occurring please open a new ticket detailing device model, android versions and if you've got a logcat output that would be really helpful (I don't have a G5 to test on).

Closing this one as the permissions issue is fixed.
