### ISSUE TITLE
Can't build example scene in Unity 2019.4.14f1 + XCode12.1 + iOS. CoreLocation.framework errror?

### ISSUE THREAD

**Issue by kidapu** [ryanw3bb/unity-native-toolkit#35]
In my enviroment, this repo shows these errors in Xcode. And can't build for iOS.

```
Showing All Messages
iPhoneOS14.1.sdk/System/Library/Frameworks/CoreLocation.framework/Headers/CLErrorDomain.h:12:1: Unknown type name 'NS_ASSUME_NONNULL_BEGIN'
iPhoneOS14.1.sdk/System/Library/Frameworks/CoreLocation.framework/Headers/CLErrorDomain.h:22:1: Expected unqualified-id
iPhoneOS14.1.sdk/System/Library/Frameworks/CoreLocation.framework/Headers/CLErrorDomain.h:24:1: Unknown type name 'NS_ASSUME_NONNULL_END'
iPhoneOS14.1.sdk/System/Library/Frameworks/CoreLocation.framework/Headers/CLError.h:12:24: Expected ';' after top level declarator
iPhoneOS14.1.sdk/System/Library/Frameworks/CoreLocation.framework/Headers/CLError.h:20:17: Unknown type name 'NSInteger'
iPhoneOS14.1.sdk/System/Library/Frameworks/CoreLocation.framework/Headers/CLError.h:20:28: Unknown type name 'CLError'
iPhoneOS14.1.sdk/System/Library/Frameworks/CoreLocation.framework/Headers/CLError.h:20:37: Function definition declared 'typedef'
iPhoneOS14.1.sdk/System/Library/Frameworks/CoreLocation.framework/Headers/CLError.h:20:9: C++ requires a type specifier for all declarations
iPhoneOS14.1.sdk/System/Library/Frameworks/CoreLocation.framework/Headers/CLError.h:21:5: Use of undeclared identifier 'kCLErrorLocationUnknown'
iPhoneOS14.1.sdk/System/Library/Frameworks/CoreLocation.framework/Headers/CLError.h:22:5: Use of undeclared identifier 'kCLErrorDenied'
iPhoneOS14.1.sdk/System/Library/Frameworks/CoreLocation.framework/Headers/CLError.h:23:5: Use of undeclared identifier 'kCLErrorNetwork'
iPhoneOS14.1.sdk/System/Library/Frameworks/CoreLocation.framework/Headers/CLError.h:24:5: Use of undeclared identifier 'kCLErrorHeadingFailure'
iPhoneOS14.1.sdk/System/Library/Frameworks/CoreLocation.framework/Headers/CLError.h:25:5: Use of undeclared identifier 'kCLErrorRegionMonitoringDenied'
iPhoneOS14.1.sdk/System/Library/Frameworks/CoreLocation.framework/Headers/CLError.h:26:5: Use of undeclared identifier 'kCLErrorRegionMonitoringFailure'
iPhoneOS14.1.sdk/System/Library/Frameworks/CoreLocation.framework/Headers/CLError.h:27:5: Use of undeclared identifier 'kCLErrorRegionMonitoringSetupDelayed'
iPhoneOS14.1.sdk/System/Library/Frameworks/CoreLocation.framework/Headers/CLError.h:28:5: Use of undeclared identifier 'kCLErrorRegionMonitoringResponseDelayed'
iPhoneOS14.1.sdk/System/Library/Frameworks/CoreLocation.framework/Headers/CLError.h:29:5: Use of undeclared identifier 'kCLErrorGeocodeFoundNoResult'
iPhoneOS14.1.sdk/System/Library/Frameworks/CoreLocation.framework/Headers/CLError.h:30:5: Use of undeclared identifier 'kCLErrorGeocodeFoundPartialResult'
iPhoneOS14.1.sdk/System/Library/Frameworks/CoreLocation.framework/Headers/CLError.h:31:5: Use of undeclared identifier 'kCLErrorGeocodeCanceled'
Too many errors emitted, stopping now
```

<img width="1083" alt="スクリーンショット 2020-11-17 22 58 32" src="https://user-images.githubusercontent.com/720154/99399042-75664780-2928-11eb-89cf-8dbabfbc027a.png">

- Mac OS X 10.15.7
- Unity 2019.4.14f1
- XCode12.1.

**Comment by kidapu** [comment]
I commented out following methods from NativeToolkit.cs

```
// [DllImport("__Internal")]
// private static extern string getLocale();

```

**Comment by ti-hardikshah** [comment]
> getLatitude

But what to do if we need Geolocation service ?? if we comment out this will work ??

**Comment by HananoshikaYomaru** [comment]
This thing broke my project too. Now I am finding a way to remove it from unity. Anyway to do it ?

**Comment by ti-hardikshah** [comment]
> This thing broke my project too. Now I am finding a way to remove it from unity. Any way to do it?

if you don't want a location functionality then just remove it from plugin >> iOS >> location related .a file 

and remove or comment code where applicable .. simple !!

**Comment by HananoshikaYomaru** [comment]
cool. Really appreciate the quick response.

**Comment by jasontrask** [comment]
Just bumped into this issue today too!

I'm not sure what caused the problem, but I have a feeling it might be something to do with Unity's change in 2019.3 which packages things up into UnityFramework within the XCode project.... but basically, it's the `Locale.h` file within this project which is causing the issue. It's conflicting with the system `<locale.h>` library and causing all these linker issues.

The simple fix is to rename Locale.h, Locale.mm (and the reference to Locale.h within Locale.mm). I renamed them to LocaleTools.h / LocaleTools.mm (no need to rename the class) and everything seems to have now built correctly within XCode. 😃

**Comment by jasontrask** [comment]
...I also had to manually add several frameworks to the UnityFramework target (AddressBook, AddressBookUI, AssetsLibrary & MessageUI). I don't remember having to do this when I used this same project in 2018.4.23f1 late last year 🤔 , so perhaps this is also a consequence of the Unity move to the UnityFramework in 2019.3?

**Comment by ti-hardikshah** [comment]
> I renamed them to Locale**Tools**.h / Locale**Tools**.mm (no need to rename the class) and everything seems to have now built correctly within

Just rename the .h and .mm file not work for me !! 

Do I need to change the Xcode project too? 
or any other changes? 
can you change and commit here?

**Comment by madBeavis** [comment]
> Just bumped into this issue today too!
> 
> I'm not sure what caused the problem, but I have a feeling it might be something to do with Unity's change in 2019.3 which packages things up into UnityFramework within the XCode project.... but basically, it's the `Locale.h` file within this project which is causing the issue. It's conflicting with the system `<locale.h>` library and causing all these linker issues.
> 
> The simple fix is to rename Locale.h, Locale.mm (and the reference to Locale.h within Locale.mm). I renamed them to Locale**Tools**.h / Locale**Tools**.mm (no need to rename the class) and everything seems to have now built correctly within XCode. 😃

thanks so much, banged my head against wall for 2 days until google seemingly randomly landed me here to find your solution.

**Comment by godboutj** [comment]
That should be fixed asap, I came very close to simply ditch the thing because of this. Also I did remove some NSString reason for the iOS PreProcessor.cs and the asset store doesn't even have the fix for the deprecated TargetGuidByName() (wich is fix into the master branch on this repos). The code behind seem legit but the packaging and distribution could use some work.

**Comment by DirtyFreddie** [comment]
> Just bumped into this issue today too!
> 
> I'm not sure what caused the problem, but I have a feeling it might be something to do with Unity's change in 2019.3 which packages things up into UnityFramework within the XCode project.... but basically, it's the `Locale.h` file within this project which is causing the issue. It's conflicting with the system `<locale.h>` library and causing all these linker issues.
> 
> The simple fix is to rename Locale.h, Locale.mm (and the reference to Locale.h within Locale.mm). I renamed them to Locale**Tools**.h / Locale**Tools**.mm (no need to rename the class) and everything seems to have now built correctly within XCode. 😃

Hi,

I have tried to do that, i have just renamed the two files, and in the Locale.mm(LocaleTools.mm) i have replaced the Locale.h with LocaleTools.h but when i build it i get the following error: 

"error: Build input file cannot be found: '/Users/DirtyFred/Documents/Build/Libraries/Plugins/iOS/NativeToolkit/Locale.mm' (in target 'UnityFramework' from project 'Unity-iPhone')"

Can you please help me out?

Thank you

**Comment by DirtyFreddie** [comment]
Also, regarding my previous question. Did you change this in the XCode project or inside unity before build?

Thank you
