### ISSUE TITLE
Location is not working

### ISSUE THREAD

**Issue by getmorphdev** [ryanw3bb/unity-native-toolkit#5]
![locationservice](https://user-images.githubusercontent.com/45969250/50154730-34a2c580-02f0-11e9-9718-6caff6bc659d.PNG)

I run the sample scene in my Samsung Galaxy s6 edge phone.
When I click the location button, I'm getting a null reference exception. The location information is not received.

**Comment by xavis** [comment]
Did you add the specific permissions to the Manifest?
