### ISSUE TITLE
Two issues

### ISSUE THREAD

**Issue by OriginLive** [ryanw3bb/unity-native-toolkit#9]
1. Android does not actually store images in gallery folder such as with 
var imageUrl = mediaClass.CallStatic<string>("insertImage", cr, image, title, description); << However this function doesn't work for me

2. I cannot build on Ios, i get invalid bitcode signature error.
Thanks

**Comment by oskar-szulc** [comment]
Invalid bitcode is also an issue for me - building on Unity Cloud Build with bitcode disabled in a build post-process.

**Comment by ryanw3bb** [comment]
Have just pushed a version of libNativeToolkit.a that has the -fembed-bitcode flags, so building with bitcode enabled should work now.
